/**
 * Implements hook_menu().
 */
function consulting_menu(){
     $items = array();

  $items['helloworld'] = array(
    'title' => 'Hello World',
    'access callback' => TRUE,
    'page callback' => 'helloworld_hello_page',
    'type' => MENU_NORMAL_ITEM,
    'menu' => 'navigation',
  );

  return $items;
}

function helloworld_hello_page() {
  return t('Hello World. Welcome to Drupal.');
}
